COLUMNS:
  'Unnamed: 0': int64
  ball: int64
  ball_no: float64
  balls_faced: int64
  balls_per_over: int64
  bat_pos: int64
  batter: category
  batter_balls: int64
  batter_runs: int64
  batting_partners: category
  batting_team: category
  bowler: category
  bowler_wicket: int64
  bowling_team: category
  city: category
  date: category
  day: int64
  event_match_no: category
  event_name: category
  extra_type: category
  fielders: category
  gender: category
  innings: int64
  match_id: int64
  match_number: category
  match_type: category
  match_won_by: category
  method: category
  month: int64
  new_batter: category
  next_batter: category
  non_striker: category
  non_striker_pos: int64
  over: int64
  overs: int64
  player_of_match: category
  player_out: category
  result_type: category
  review_batter: category
  review_decision: category
  runs_batter: int64
  runs_bowler: int64
  runs_extras: int64
  runs_not_boundary: bool
  runs_target: float64
  runs_total: int64
  season: category
  stage: category
  striker_out: bool
  superover_winner: category
  team_balls: int64
  team_reviewed: category
  team_runs: int64
  team_type: category
  team_wicket: int64
  toss_decision: category
  toss_winner: category
  umpire: category
  umpires_call: bool
  valid_ball: int64
  venue: category
  wicket_kind: category
  win_outcome: category
  year: int64
DATA_INFO:
  columns: 64
  file_name: IPL.csv
  file_type: csv
  rows: 278205
TARGET_COLUMN:
  name: runs_not_boundary
