COLUMNS:
  alcohol: float64
  chlorides: float64
  citric acid: float64
  density: float64
  fixed acidity: float64
  free sulfur dioxide: float64
  pH: float64
  quality: int64
  residual sugar: float64
  sulphates: float64
  total sulfur dioxide: float64
  volatile acidity: float64
DATA_INFO:
  columns: 12
  file_name: winequality-red.csv
  file_type: csv
  rows: 1599
TARGET_COLUMN:
  name: quality
